src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use AppBundle\Form\ProfileSettings;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @UniqueEntity(fields={"email", "username"})
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser implements UserInterface
{

    use BaseEntity;

    const ROLE_USER = 'ROLE_USER';

    const GENDER_FEMALE = 1;
    const GENDER_MALE = 2;

    const SIDE_MENU_FOLLOWS_COUNT = 6;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned"=true})
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    protected $id;

    /**
     * @Assert\NotNull()
     * @Assert\Length(min="4")
     * @ORM\Column(type="string", nullable=true)
     * @var string
     */
    protected $fullName;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string
     */
    protected $location;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @var string
     */
    protected $biography;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string
     */
    protected $website;

    /**
     * @Assert\NotBlank()
     * @Assert\Date()
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    protected $bornAt;

    /**
     * @Assert\Choice(choices={User::GENDER_FEMALE, User::GENDER_MALE})
     * @ORM\Column(type="smallint", nullable=true)
     * @var int
     */
    protected $gender;

    /**
     * ORM\Column(type="string", nullable=true)
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Locale")
     * @ORM\JoinColumn(name="locale_code", referencedColumnName="code", onDelete="SET NULL")
     * @var string
     */
    protected $locale;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\UserSocials", mappedBy="user", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     * @var UserSocials
     */
    protected $userSocials;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    protected $answersCount = 0;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    protected $likesCount = 0;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    protected $followersCount = 0;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    protected $followedCount = 0;

    /**
     * @Assert\Range(min="0",  max="17")
     * @ORM\Column(type="smallint", name="theme_id")
     * @var int
     */
    protected $theme = 0;

    /**
     * @Assert\Range(min="0", max="49")
     * @ORM\Column(type="smallint", name="emoodji_id")
     * @var int
     */
    protected $emoodji = 0;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $allowAnonymousQuestions = true;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $allowAnswerSharing = true;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $allowSubscribing = true;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $allowDiscovery = true;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $showOnlineStatus = true;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $newQuestionEmail = true;

    /**
     * @var boolean
     */
    protected $followedByViewer = false;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Follow", mappedBy="followed", cascade={"remove"})
     */
    protected $followers;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Follow", mappedBy="follower", cascade={"remove"})
     */
    protected $followed;

    /**
     * @return string
     */
    public function getFullName()
    {
        return $this->fullName;
    }

    /**
     * @return string
     */
    public function getDisplayName()
    {
        return $this->fullName ?? $this->username;
    }

    /**
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param string $location
     * @return $this
     */
    public function setLocation(string $location)
    {
        $this->location = $location;
        return $this;
    }

    /**
     * @return string
     */
    public function getBiography()
    {
        return $this->biography;
    }

    /**
     * @param string $biography
     * @return $this
     */
    public function setBiography(string $biography)
    {
        $this->biography = $biography;
        return $this;
    }

    /**
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    /**
     * @param mixed $website
     * @return $this
     */
    public function setWebsite(string $website)
    {
        $this->website = $website;
        return $this;
    }

    /**
     * @param string $fullName
     * @return $this
     */
    public function setFullName(string $fullName)
    {
        $this->fullName = $fullName;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getBornAt()
    {
        return $this->bornAt;
    }

    /**
     * @param \DateTime $bornAt
     * @return $this
     */
    public function setBornAt($bornAt)
    {
        $this->bornAt = $bornAt;
        return $this;
    }

    /**
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param int $gender
     * @return $this
     */
    public function setGender($gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * @param string $locale
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;
        return $this;
    }

    /**
     * @return UserSocials
     */
    public function getUserSocials()
    {
        return $this->userSocials;
    }

    /**
     * @param UserSocials $userSocials
     * @return $this
     */
    public function setUserSocials(UserSocials $userSocials)
    {
        $this->userSocials = $userSocials;
        return $this;
    }

    /**
     * @return int
     */
    public function getAnswersCount()
    {
        return $this->answersCount;
    }

    /**
     * @param int $answersCount
     * @return $this
     */
    public function setAnswersCount(int $answersCount)
    {
        $this->answersCount = $answersCount;
        return $this;
    }

    /**
     * @return int
     */
    public function getLikesCount()
    {
        return $this->likesCount;
    }

    /**
     * @param int $likesCount
     * @return $this
     */
    public function setLikesCount(int $likesCount)
    {
        $this->likesCount = $likesCount;
        return $this;
    }

    /**
     * @return int
     */
    public function getFollowersCount()
    {
        return $this->followersCount;
    }

    /**
     * @param int $followersCount
     * @return $this
     */
    public function setFollowersCount(int $followersCount)
    {
        $this->followersCount = $followersCount;
        return $this;
    }

    /**
     * @return int
     */
    public function getFollowedCount()
    {
        return $this->followedCount;
    }

    /**
     * @param int $followedCount
     * @return $this
     */
    public function setFollowedCount(int $followedCount)
    {
        $this->followedCount = $followedCount;
        return $this;
    }

    /**
     * @return int
     */
    public function getTheme(): int
    {
        return $this->theme;
    }

    /**
     * @param int $theme
     * @return $this
     */
    public function setTheme(int $theme)
    {
        $this->theme = $theme;
        return $this;
    }

    /**
     * @return int
     */
    public function getEmoodji(): int
    {
        return $this->emoodji;
    }

    /**
     * @param int $emoodji
     * @return $this
     */
    public function setEmoodji(int $emoodji)
    {
        $this->emoodji = $emoodji;
        return $this;
    }

    /**
     * @return bool
     */
    public function isAllowAnonymousQuestions(): bool
    {
        return $this->allowAnonymousQuestions;
    }

    /**
     * @param bool $allowAnonymousQuestions
     * @return $this
     */
    public function setAllowAnonymousQuestions(bool $allowAnonymousQuestions)
    {
        $this->allowAnonymousQuestions = $allowAnonymousQuestions;
        return $this;
    }

    /**
     * @return bool
     */
    public function isAllowAnswerSharing(): bool
    {
        return $this->allowAnswerSharing;
    }

    /**
     * @param bool $allowAnswerSharing
     * @return $this
     */
    public function setAllowAnswerSharing(bool $allowAnswerSharing)
    {
        $this->allowAnswerSharing = $allowAnswerSharing;
        return $this;
    }

    /**
     * @return bool
     */
    public function isAllowSubscribing(): bool
    {
        return $this->allowSubscribing;
    }

    /**
     * @param bool $allowSubscribing
     * @return $this
     */
    public function setAllowSubscribing(bool $allowSubscribing)
    {
        $this->allowSubscribing = $allowSubscribing;
        return $this;
    }

    /**
     * @return bool
     */
    public function isAllowDiscovery(): bool
    {
        return $this->allowDiscovery;
    }

    /**
     * @param bool $allowDiscovery
     * @return $this
     */
    public function setAllowDiscovery(bool $allowDiscovery)
    {
        $this->allowDiscovery = $allowDiscovery;
        return $this;
    }

    /**
     * @return bool
     */
    public function isShowOnlineStatus(): bool
    {

src/AppBundle/Resources/views/Partials/auth_socials.html.twig
{% for owner in hwi_oauth_resource_owners() %}
    <a class="loginService icon-{{ owner }}-solo" data-action="ButtonPostOnce"
       data-url="{{ hwi_oauth_login_url(owner) }}" data-window="_blank"></a>
{% endfor %}

src/AppBundle/Resources/views/Partials/header.html.twig
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ app.user ? path('site_account_wall') : path('site_homepage') }}">Asker</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {{ knp_menu_render('AppBundle:Main:mainMenu') }}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

src/AppBundle/Resources/views/Partials/side_ask_friends.html.twig
<div class="ask-box side-section">
    <h3>Спросите у друзей</h3>
    <form id="askForm" data-gtm="{&quot;name&quot;:&quot;popup&quot;,&quot;meta&quot;:[&quot;mass-question&quot;,&quot;Mass questions&quot;,&quot;New&quot;]}" data-action="PopupOpen" action="{{ path('site_account_ask_friends') }}" accept-charset="UTF-8" method="post">
        <input type="hidden" name="_method" value="put" />
        <div class="question">
            <textarea placeholder="Напишите ваш вопрос" data-counter=".optionsBar-counter" data-limit="300" data-atcomplete="/account/friends/autocomplete" name="question_text" id="question_question_text"></textarea>
        </div>
        <div class="optionsBar">
            <button name="button" type="submit" class="btn-primary rsp-eql-desktop">Спросить</button>
            <div class="optionsBar-option optionsBar-counter"></div>
            <input name="anonymous" type="hidden" value="0" />
            <input class="checkbox" id="mini_question_anonymous" type="checkbox" value="true" checked="checked" name="anonymous" />
            <label for="mini_question_anonymous" class="optionsBar-askMode">
                <span>Анонимный вопрос</span>
            </label>
        </div>
    </form>
</div>

src/AppBundle/Resources/views/Partials/side_last_friends.html.twig
{% if app.user.followedCount > 0 %}
    <div class="side-section">
        <h3>Ваши друзья</h3>
        {% for user in follows %}
            <div class="item streamItem streamItem-user">
                <a class="btn-secondary icon-caret-right" href="{{ path('site_profile_ask', {username: user.username}) }}">Спросить</a>
                <a style="background-image:url(https://akimg3.ask.fm/732/7e950/7af8/4c37/bd62/0ad0b08f7a3d/thumb/69570.png)" class="askfm-avatar45 emoodji-user emoodji42-user" href="{{ path('site_profile_show', {username: user.username}) }}"></a>
                <a class="streamItemWallContent streamItemContent-user" href="{{ path('site_profile_show', {username: user.username}) }}">
                    <span class="blockLink">{{ user.displayName }}</span>
                    <span class="blockLink" dir="ltr">@{{ user.username }}</span>
                </a>
            </div>
        {% endfor %}
        {% if app.user.followedCount > constant('SIDE_MENU_FOLLOWS_COUNT', app.user) %}
            <p><a href="/account/friends">Показать всех друзей</a></p>
        {% endif %}
    </div>
{% endif %}